### ISSUE TITLE
Pig-solr doesn't support basic authentication

### ISSUE THREAD

**Issue by smschauhan** [lucidworks/pig-solr#3]
I didn't see any configuration options for basic authentication. 
https://lucidworks.com/blog/2015/08/17/securing-solr-basic-auth-permission-rules/

**Comment by smschauhan** [comment]
@acesar : Here is what I have tried so far - 
I bumped up the Solrj version to 5.4.1, given basicAuth was added to Solrj [here](https://cwiki.apache.org/confluence/display/solr/Basic+Authentication+Plugin).
As per the doc, looks like the credentials need to be set with every request.
so I modified 

> solr-hadoop-common/solr-hadoop-io/src/main/java/com/lucidworks/hadoop/io/LucidWorksWriter.java


```
 UpdateRequest req = new UpdateRequest();
      req.setParams(params);
      req.add(buffer);
      solr.request(req);
```

to 
```
 UpdateRequest req = new UpdateRequest();
      req.setParams(params);
      req.setBasicAuthCredentials("solr","solrRocks");
      req.add(buffer);
      solr.request(req);
```
hoping it would be that simple :)

Obviously, that didn't work and I started looking at the test cases to find an example of Basic Auth for ConcurrentUpdateSolrClient but couldn't find anything. 

I think it's safe to assume that we will have to create a ConcurrentUpdateSolrClient while supplying our own HttpClient instead of using the internally managed HttpClient https://github.com/apache/lucene-solr/blob/branch_5_4/solr/solrj/src/java/org/apache/solr/client/solrj/impl/ConcurrentUpdateSolrClient.java#L100.

I wanted to check with you if I am on the right track?

**Comment by acesar** [comment]
@smschauhan : I didn't want to tackle this one yet because it needs a Solrj upgrade. 
However, the change you made seems correct. The `sendBuffer()` has some logic to not create an `UpdateRequest ` if not needed. Maybe, you can change it to always create an `UpdateRequest`.

From [here] 
(https://cwiki.apache.org/confluence/display/solr/Authentication+and+Authorization+Plugins#AuthenticationandAuthorizationPlugins-EnabledPluginswithsecurity.json) `Basic authentication: SolrCloud only.`. So, your pig script should be using the zookeeper string `set solr.zkhost '$zkHost';` and `LucidWorksWriter` should create a `CloudSolrClient` instead of a `ConcurrentUpdateSolrClient`.

**Comment by smschauhan** [comment]
@acesar Thanks for your response, appreciate it. I completely understand your reservation, would be bad for everyone to have to upgrade to Solr >5.4.0. 
I did that exact change but the request failed again. I have a $zkHost and a CloudSolrClient is failing.
```
2016-02-19 13:19:31,574 INFO [main] com.lucidworks.hadoop.io.LucidWorksWriter: Sending 500 documents
2016-02-19 13:19:32,314 ERROR [main] shaded.org.apache.solr.client.solrj.impl.CloudSolrClient: Request to collection demo failed due to (401) shaded.org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at https://localhost:8983/solr/demo_shard2_replica1: Expected mime type application/octet-stream but got text/html. <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 401 Unauthorized request, Response code: 401</title>
</head>
<body><h2>HTTP ERROR 401</h2>
<p>Problem accessing /solr/demo_shard2_replica1/update. Reason:
<pre>    Unauthorized request, Response code: 401</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
, retry? 0
```

**Comment by smschauhan** [comment]
@cesar - Ok, I think I hit https://issues.apache.org/jira/browse/SOLR-8640.

**Comment by acesar** [comment]
I saw the issue, Solrj 5.5.0 is on maven central already you can give it a try.

**Comment by smschauhan** [comment]
@acesar It works perfectly :+1:  Could you declare variables so that I can pass the username and password?

This is what my code looks like today - 
```
protected void sendBuffer() throws SolrServerException, IOException {
    log.info("Sending {} documents", buffer.size());
    //flush the buffer
    //if (params == null) {
    //  solr.add(buffer);
    //} else {
      UpdateRequest req = new UpdateRequest();
      req.setParams(params);
      req.add(buffer);
      req.setBasicAuthCredentials("solr","SolrRocks");
      solr.request(req);
  //  }
    buffer.clear();
    //this shouldn't get hit if there are exceptions, so it should be fine here as part of our retry logic
  }
```
I didn't have to make any other changes to the the code. 

One more questions - If I wanted to increase the buffer size, that can be done by increasing "lww.buffer.docs.size" through 

1set lww.buffer.docs.size 1000;
`
Correct?

**Comment by smschauhan** [comment]
Sorry, I had to reopen the issues because now the request fails after running to 19-20 min.
Here is the log. I am unable to figure out why it fails after successfully running one cycle. 
`2016-02-22 14:27:26,745 INFO [main] com.lucidworks.hadoop.io.LucidWorksWriter: Sending 500 documents
2016-02-22 14:27:26,909 INFO [main] com.lucidworks.hadoop.io.LucidWorksWriter: Sending 500 documents
2016-02-22 14:27:27,089 INFO [main] com.lucidworks.hadoop.io.LucidWorksWriter: Sending 500 documents
2016-02-22 14:27:27,277 INFO [main] com.lucidworks.hadoop.io.LucidWorksWriter: Sending 500 documents
2016-02-22 14:27:27,456 INFO [main] com.lucidworks.hadoop.io.LucidWorksWriter: Sending 500 documents
2016-02-22 14:27:27,609 INFO [main] com.lucidworks.hadoop.io.LucidWorksWriter: Sending 500 documents
2016-02-22 14:27:27,784 INFO [main] com.lucidworks.hadoop.io.LucidWorksWriter: Closing the Writer
2016-02-22 14:27:27,784 INFO [main] com.lucidworks.hadoop.io.LucidWorksWriter: Sending 336 documents
2016-02-22 14:27:27,929 INFO [main] com.lucidworks.hadoop.io.LucidWorksWriter: Done sending docs
2016-02-22 14:27:27,972 INFO [main] org.apache.zookeeper.ZooKeeper: Session: 0x34f4fa7bc4f0100 closed
2016-02-22 14:27:27,972 INFO [main-EventThread] org.apache.zookeeper.ClientCnxn: EventThread shut down
2016-02-22 14:27:27,974 INFO [main] org.apache.hadoop.mapred.Task: Task:attempt_1455503708297_122421_m_000004_2 is done. And is in the process of committing
2016-02-22 14:27:28,028 INFO [main] org.apache.hadoop.mapred.Task: Task attempt_1455503708297_122421_m_000004_2 is allowed to commit now
2016-02-22 14:27:28,032 INFO [main] com.lucidworks.hadoop.io.LucidWorksWriter: Opening LucidWorksWriter for PigLatin:test.pig
2016-02-22 14:27:28,032 INFO [main] com.lucidworks.hadoop.io.LucidWorksWriter: Indexing to collection: demo w/ ZK host: zlt00871.vci.att.com:2181,zlt00872.vci.att.com:2181,zlt00873.vci.att.com:2181/gofish
2016-02-22 14:27:28,032 INFO [main] shaded.org.apache.solr.common.cloud.SolrZkClient: Using default ZkCredentialsProvider
2016-02-22 14:27:28,032 INFO [main] org.apache.zookeeper.ZooKeeper: Initiating client connection, connectString=zlt00871.vci.att.com:2181,zlt00872.vci.att.com:2181,zlt00873.vci.att.com:2181/gofish sessionTimeout=10000 watcher=shaded.org.apache.solr.common.cloud.SolrZkClient$3@1f1f4c7a
2016-02-22 14:27:28,034 INFO [main] shaded.org.apache.solr.common.cloud.ConnectionManager: Waiting for client to connect to ZooKeeper
2016-02-22 14:27:28,035 INFO [main-SendThread(zlt00872.vci.att.com:2181)] org.apache.zookeeper.ClientCnxn: Opening socket connection to server zlt00872.vci.att.com/135.41.214.119:2181. Will not attempt to authenticate using SASL (unknown error)
2016-02-22 14:27:28,078 INFO [main-SendThread(zlt00872.vci.att.com:2181)] org.apache.zookeeper.ClientCnxn: Socket connection established to zlt00872.vci.att.com/135.41.214.119:2181, initiating session
2016-02-22 14:27:28,127 INFO [main-SendThread(zlt00872.vci.att.com:2181)] org.apache.zookeeper.ClientCnxn: Session establishment complete on server zlt00872.vci.att.com/135.41.214.119:2181, sessionid = 0x24f4fa7e35e007d, negotiated timeout = 10000
2016-02-22 14:27:28,128 INFO [zkCallback-4-thread-1] shaded.org.apache.solr.common.cloud.ConnectionManager: Watcher shaded.org.apache.solr.common.cloud.ConnectionManager@4b7e0e67 name:ZooKeeperConnection Watcher:zlt00871.vci.att.com:2181,zlt00872.vci.att.com:2181,zlt00873.vci.att.com:2181/gofish got event WatchedEvent state:SyncConnected type:None path:null path:null type:None
2016-02-22 14:27:28,128 INFO [main] shaded.org.apache.solr.common.cloud.ConnectionManager: Client is connected to ZooKeeper
2016-02-22 14:27:28,128 INFO [main] shaded.org.apache.solr.common.cloud.SolrZkClient: Using default ZkACLProvider
2016-02-22 14:27:28,128 INFO [main] shaded.org.apache.solr.common.cloud.ZkStateReader: Updating cluster state from ZooKeeper... 
2016-02-22 14:27:29,013 ERROR [main] shaded.org.apache.solr.client.solrj.impl.CloudSolrClient: Request to collection demo failed due to (401) shaded.org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at https://zlt00873.vci.att.com:8983/solr/demo: Expected mime type application/octet-stream but got text/html. <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 401 Unauthorized request, Response code: 401</title>
</head>
<body><h2>HTTP ERROR 401</h2>
<p>Problem accessing /solr/demo/update. Reason:
<pre>    Unauthorized request, Response code: 401</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
, retry? 0
2016-02-22 14:27:29,014 WARN [main] org.apache.hadoop.mapred.YarnChild: Exception running child : shaded.org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at https://zlt00873.vci.att.com:8983/solr/demo: Expected mime type application/octet-stream but got text/html. <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 401 Unauthorized request, Response code: 401</title>
</head>
<body><h2>HTTP ERROR 401</h2>
<p>Problem accessing /solr/demo/update. Reason:
<pre>    Unauthorized request, Response code: 401</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>

	at shaded.org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:544)
	at shaded.org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:240)
	at shaded.org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:229)
	at shaded.org.apache.solr.client.solrj.impl.LBHttpSolrClient.doRequest(LBHttpSolrClient.java:372)
	at shaded.org.apache.solr.client.solrj.impl.LBHttpSolrClient.request(LBHttpSolrClient.java:325)
	at shaded.org.apache.solr.client.solrj.impl.CloudSolrClient.sendRequest(CloudSolrClient.java:1099)
	at shaded.org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:870)
	at shaded.org.apache.solr.client.solrj.impl.CloudSolrClient.request(CloudSolrClient.java:806)
	at shaded.org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
	at shaded.org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:482)
	at shaded.org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:501)
	at com.lucidworks.hadoop.io.LucidWorksWriter.commit(LucidWorksWriter.java:247)
	at com.lucidworks.hadoop.io.LWMapReduceOutputFormat$2.commitTask(LWMapReduceOutputFormat.java:75)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigOutputCommitter.commitTask(PigOutputCommitter.java:356)
	at org.apache.hadoop.mapred.Task.commit(Task.java:1163)
	at org.apache.hadoop.mapred.Task.done(Task.java:1025)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:345)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

2016-02-22 14:27:29,016 INFO [main] org.apache.hadoop.mapred.Task: Runnning cleanup for the task`

**Comment by acesar** [comment]
@smschauhan The issue should remain open until a fix is committed.

From the logs that you added, it seems the data got indexed into Solr, however the final commit was not successful (Unauthorized).

You can add  another `UpdateRequest` with the credentials into the [commit method](https://github.com/lucidworks/solr-hadoop-common/blob/master/solr-hadoop-io/src/main/java/com/lucidworks/hadoop/io/LucidWorksWriter.java#L245)

**Comment by smschauhan** [comment]
Ok, that was it. I changed 
```
  public void commit() throws IOException, SolrServerException {
    solr.commit(false, false);
  }
```
to
``` 
 public void commit() throws IOException, SolrServerException {
     UpdateRequest req = new UpdateRequest();
      req.setAction( UpdateRequest.ACTION.COMMIT, false, false );
      req.setBasicAuthCredentials("solr","SolrRocks");
      solr.request(req);
  }
```
and that worked. I am doing some performance measurements now, and it took 9M records in about 16 min. I am going to try and boost up the performance by increasing lww.buffer.docs.size.

**Comment by smschauhan** [comment]
Ok, here are the performance metrics. 9M docs, 2 shards, 2 replicas. 

lww.buffer.docs.size Time
500 16
2000 10
10000 7
20000 6

The scaling factors will be different if you have a higher number of shards.
