### ISSUE TITLE
Failed to build solr index using Pig

### ISSUE THREAD

**Issue by aftnix** [lucidworks/pig-solr#8]
```
grunt> STORE A INTO 'solr' USING com.lucidworks.hadoop.pig.SolrStoreFunc();

2016-09-27 11:19:26,289 [PigTezLauncher-0] INFO  org.apache.pig.backend.hadoop.executionengine.tez.TezJob - DAG Status: status=FAILED, progress=T
otalTasks: 1 Succeeded: 0 Running: 0 Failed: 1 Killed: 0 FailedTaskAttempts: 4, diagnostics=Vertex failed, vertexName=scope-5, vertexId=vertex_14
74881768573_0013_2_00, diagnostics=[Task failed, taskId=task_1474881768573_0013_2_00_000000, diagnostics=[TaskAttempt 0 failed, info=[Error: Fail
ure while running task:org.apache.pig.backend.executionengine.ExecException: ERROR 2135: Received error from store function.java.io.IOException: 
java.lang.ClassCastException: org.joda.time.DateTime cannot be cast to java.lang.String
        at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POStoreTez.getNextTuple(POStoreTez.java:148)
        at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.runPipeline(PigProcessor.java:376)
        at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.run(PigProcessor.java:241)
        at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:347)
        at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:194)
        at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:185)

```

**Comment by aftnix** [comment]
Turns out there is something wrong with converting a TIMESTAMP typed column from Hive to solr. After it was changed, no more exceptions are thrown.

But it the job is now stuck. Just like what happened in hive-solr module. Job is just stuck. it never progresses.

**Comment by acesar** [comment]
@aftnix 
> Job is just stuck. it never progresses.

That seems to be a problem with the configuration of the hadoop yarn service. 

- Can you run the example word count job?
https://hadoop.apache.org/docs/r2.7.2/hadoop-mapreduce-client/hadoop-mapreduce-client-core/MapReduceTutorial.html#Example:_WordCount_v2.0

- If you are able to run the example job, then re-run the Pig job and please share your yarn logs.
